// 符号速选数据（分类，参考 MathType / AxMath）与分类英文名。
// 从 taskpane.js 抽出的纯数据，便于维护；逻辑仍在 taskpane.js。
// 每项 { l: 按钮显示, m?: 富文本预览, i: 插入的 LaTeX, d?: 短描述, t?: 悬停说明 }；#0 为插入后光标占位。

export const SYMBOL_CATEGORIES = [
  {
    name: "常用",
    items: [
      { l: "□/□", m: "<span class=\"sym-frac\"><span>□</span><span>□</span></span>", d: "分数", i: "\\frac{#0}{#0}", t: "分数" },
      { l: "√□", d: "平方根", i: "\\sqrt{#0}", t: "平方根" },
      { l: "ⁿ√□", m: "<sup>n</sup>√□", d: "n 次根", i: "\\sqrt[#0]{#0}", t: "n 次根" },
      { l: "x^□", m: "x<sup>□</sup>", d: "上标", i: "x^{#0}", t: "上标" },
      { l: "x_□", m: "<span class=\"sym-subonly\"><span>x</span><sub>□</sub></span>", d: "下标", i: "x_{#0}", t: "下标" },
      { l: "x_□^□", m: "<span class=\"sym-subsup\"><span>x</span><span><sup>□</sup><sub>□</sub></span></span>", d: "上下标", i: "x_{#0}^{#0}", t: "上下标" },
      { l: "(□)", d: "圆括号", i: "\\left(#0\\right)", t: "圆括号" },
      { l: "[□]", d: "方括号", i: "\\left[#0\\right]", t: "方括号" },
      { l: "{□}", d: "花括号", i: "\\left\\{#0\\right\\}", t: "花括号" },
      { l: "|□|", d: "绝对值", i: "\\left|#0\\right|", t: "绝对值" },
      { l: "‖□‖", d: "范数", i: "\\left\\|#0\\right\\|", t: "范数" },
      { l: "⌊□⌋", d: "向下取整", i: "\\left\\lfloor #0\\right\\rfloor", t: "向下取整" },
      { l: "⌈□⌉", d: "向上取整", i: "\\left\\lceil #0\\right\\rceil", t: "向上取整" },
      { l: "(□□)", m: "(<span class=\"sym-stack\"><span>□</span><span>□</span></span>)", d: "二项式", i: "\\binom{#0}{#0}", t: "二项式系数" },
      { l: "▦", d: "矩阵", i: "\\begin{pmatrix}#0\\end{pmatrix}", t: "矩阵" },
      { l: "{□", d: "分段", i: "\\begin{cases}#0\\end{cases}", t: "分段函数" },
      { l: "≣", d: "对齐", i: "\\begin{aligned}#0 &= #0\\end{aligned}", t: "对齐公式组（按 ↵ 增行）" },
      { l: "x⃗", m: "<span class=\"sym-accent\"><span class=\"sym-accent-mark arrow\">→</span><span>x</span></span>", d: "向量", i: "\\vec{x}", t: "向量" },
      { l: "AB⃗", m: "<span class=\"sym-accent wide\"><span class=\"sym-accent-mark arrow\">→</span><span>AB</span></span>", d: "长向量", i: "\\overrightarrow{AB}", t: "有向线段 / 长向量" },
      { l: "x̄", m: "<span class=\"sym-overline\">x</span>", d: "上划线", i: "\\overline{x}", t: "上划线" },
      { l: "x̲", m: "<span class=\"sym-underline\">x</span>", d: "下划线", i: "\\underline{x}", t: "下划线" },
      { l: "x̂", m: "<span class=\"sym-accent\"><span class=\"sym-accent-mark\">ˆ</span><span>x</span></span>", d: "帽", i: "\\hat{x}", t: "帽（estimate）" },
      { l: "x̃", m: "<span class=\"sym-accent\"><span class=\"sym-accent-mark\">˜</span><span>x</span></span>", d: "波浪号", i: "\\tilde{x}", t: "波浪号" },
      { l: "ẋ", m: "<span class=\"sym-accent\"><span class=\"sym-accent-mark\">˙</span><span>x</span></span>", d: "一阶导", i: "\\dot{x}", t: "一阶导（点）" },
      { l: "ẍ", m: "<span class=\"sym-accent\"><span class=\"sym-accent-mark\">¨</span><span>x</span></span>", d: "二阶导", i: "\\ddot{x}", t: "二阶导（双点）" },
      { l: "⏞□", m: "<span class=\"sym-brace over\"><span>⏞</span><span>□</span></span>", d: "上花括", i: "\\overbrace{#0}", t: "上花括（标注）" },
      { l: "⏟□", m: "<span class=\"sym-brace under\"><span>□</span><span>⏟</span></span>", d: "下花括", i: "\\underbrace{#0}", t: "下花括（标注）" },
    ],
  },
  {
    name: "运算符",
    items: [
      { l: "+", i: "+" },
      { l: "−", i: "-" },
      { l: "±", i: "\\pm" },
      { l: "∓", i: "\\mp" },
      { l: "×", i: "\\times" },
      { l: "÷", i: "\\div" },
      { l: "⋅", i: "\\cdot" },
      { l: "∗", i: "\\ast" },
      { l: "⋆", i: "\\star" },
      { l: "∘", i: "\\circ" },
      { l: "∙", i: "\\bullet" },
      { l: "⊕", i: "\\oplus" },
      { l: "⊖", i: "\\ominus" },
      { l: "⊗", i: "\\otimes" },
      { l: "⊙", i: "\\odot" },
      { l: "⊘", i: "\\oslash" },
      { l: "⊞", i: "\\boxplus" },
      { l: "⊠", i: "\\boxtimes" },
      { l: "⊎", i: "\\uplus" },
      { l: "⊓", i: "\\sqcap" },
      { l: "⊔", i: "\\sqcup" },
      { l: "⋄", i: "\\diamond" },
      { l: "△", i: "\\bigtriangleup" },
      { l: "▽", i: "\\bigtriangledown" },
      { l: "◁", i: "\\triangleleft" },
      { l: "▷", i: "\\triangleright" },
      { l: "†", i: "\\dagger" },
      { l: "‡", i: "\\ddagger" },
      { l: "∖", i: "\\setminus" },
      { l: "≀", i: "\\wr" },
      { l: "⨿", i: "\\amalg" },
    ],
  },
  {
    name: "关系符",
    items: [
      { l: "=", i: "=" },
      { l: "≠", i: "\\neq" },
      { l: "≈", i: "\\approx" },
      { l: "≡", i: "\\equiv" },
      { l: "≅", i: "\\cong" },
      { l: "∼", i: "\\sim" },
      { l: "≃", i: "\\simeq" },
      { l: "<", i: "<" },
      { l: ">", i: ">" },
      { l: "≤", i: "\\leq" },
      { l: "≥", i: "\\geq" },
      { l: "≪", i: "\\ll" },
      { l: "≫", i: "\\gg" },
      { l: "≺", i: "\\prec" },
      { l: "≻", i: "\\succ" },
      { l: "≼", i: "\\preceq" },
      { l: "≽", i: "\\succeq" },
      { l: "≰", i: "\\nleq" },
      { l: "≱", i: "\\ngeq" },
      { l: "∝", i: "\\propto" },
      { l: "⊥", i: "\\perp" },
      { l: "∥", i: "\\parallel" },
      { l: "≐", i: "\\doteq" },
      { l: "≍", i: "\\asymp" },
      { l: "≜", i: "\\triangleq", t: "定义为" },
      { l: "⊨", i: "\\models" },
      { l: "⊢", i: "\\vdash" },
      { l: "⊣", i: "\\dashv" },
      { l: "⋈", i: "\\bowtie" },
    ],
  },
  {
    name: "箭头",
    items: [
      { l: "→", i: "\\rightarrow" },
      { l: "←", i: "\\leftarrow" },
      { l: "↔", i: "\\leftrightarrow" },
      { l: "↑", i: "\\uparrow" },
      { l: "↓", i: "\\downarrow" },
      { l: "↕", i: "\\updownarrow" },
      { l: "⇑", i: "\\Uparrow" },
      { l: "⇓", i: "\\Downarrow" },
      { l: "⇕", i: "\\Updownarrow" },
      { l: "⇒", i: "\\Rightarrow" },
      { l: "⇐", i: "\\Leftarrow" },
      { l: "⇔", i: "\\Leftrightarrow" },
      { l: "↦", i: "\\mapsto" },
      { l: "⟼", i: "\\longmapsto" },
      { l: "⇌", i: "\\rightleftharpoons", t: "可逆 / 平衡" },
      { l: "⟶", i: "\\longrightarrow" },
      { l: "⟵", i: "\\longleftarrow" },
      { l: "↠", i: "\\twoheadrightarrow" },
      { l: "↗", i: "\\nearrow" },
      { l: "↘", i: "\\searrow" },
      { l: "↖", i: "\\nwarrow" },
      { l: "↙", i: "\\swarrow" },
      { l: "⇀", i: "\\rightharpoonup" },
      { l: "↪", i: "\\hookrightarrow" },
    ],
  },
  {
    name: "大型运算",
    items: [
      { l: "∑", i: "\\sum_{#0}^{#0}", t: "求和" },
      { l: "∏", i: "\\prod_{#0}^{#0}", t: "连乘" },
      { l: "∐", i: "\\coprod_{#0}^{#0}", t: "余积" },
      { l: "∫", i: "\\int_{#0}^{#0}", t: "积分" },
      { l: "∬", i: "\\iint", t: "二重积分" },
      { l: "∭", i: "\\iiint", t: "三重积分" },
      { l: "∮", i: "\\oint", t: "环路积分" },
      { l: "⋃", i: "\\bigcup_{#0}^{#0}", t: "并" },
      { l: "⋂", i: "\\bigcap_{#0}^{#0}", t: "交" },
      { l: "⊔", i: "\\bigsqcup_{#0}^{#0}", t: "不交并" },
      { l: "⋁", i: "\\bigvee_{#0}^{#0}", t: "析取" },
      { l: "⋀", i: "\\bigwedge_{#0}^{#0}", t: "合取" },
      { l: "⨄", i: "\\biguplus_{#0}^{#0}" },
      { l: "⨁", i: "\\bigoplus_{#0}^{#0}" },
      { l: "⨂", i: "\\bigotimes_{#0}^{#0}" },
      { l: "⨀", i: "\\bigodot_{#0}^{#0}" },
      { l: "lim", i: "\\lim_{#0}", t: "极限" },
      { l: "limsup", i: "\\limsup_{#0}", t: "上极限" },
      { l: "liminf", i: "\\liminf_{#0}", t: "下极限" },
      { l: "max", i: "\\max_{#0}", t: "最大值" },
      { l: "min", i: "\\min_{#0}", t: "最小值" },
      { l: "sup", i: "\\sup_{#0}", t: "上确界" },
      { l: "inf", i: "\\inf_{#0}", t: "下确界" },
    ],
  },
  {
    name: "集合逻辑",
    items: [
      { l: "∈", i: "\\in" },
      { l: "∉", i: "\\notin" },
      { l: "∋", i: "\\ni" },
      { l: "⊂", i: "\\subset" },
      { l: "⊆", i: "\\subseteq" },
      { l: "⊊", i: "\\subsetneq" },
      { l: "⊄", i: "\\not\\subset" },
      { l: "⊃", i: "\\supset" },
      { l: "⊇", i: "\\supseteq" },
      { l: "∪", i: "\\cup" },
      { l: "∩", i: "\\cap" },
      { l: "∅", i: "\\emptyset" },
      { l: "∁", i: "\\complement", t: "补集" },
      { l: "∀", i: "\\forall" },
      { l: "∃", i: "\\exists" },
      { l: "∄", i: "\\nexists" },
      { l: "∧", i: "\\land" },
      { l: "∨", i: "\\lor" },
      { l: "¬", i: "\\neg" },
      { l: "⊤", i: "\\top", t: "真" },
      { l: "⊥", i: "\\bot", t: "假" },
      { l: "⟹", i: "\\implies" },
      { l: "⟺", i: "\\iff" },
      { l: "∴", i: "\\therefore" },
      { l: "∵", i: "\\because" },
      { l: "ℕ", i: "\\mathbb{N}", t: "自然数集" },
      { l: "ℤ", i: "\\mathbb{Z}", t: "整数集" },
      { l: "ℚ", i: "\\mathbb{Q}", t: "有理数集" },
      { l: "ℝ", i: "\\mathbb{R}", t: "实数集" },
      { l: "ℂ", i: "\\mathbb{C}", t: "复数集" },
    ],
  },
  {
    name: "希腊字母",
    items: [
      { l: "α", i: "\\alpha" },
      { l: "β", i: "\\beta" },
      { l: "γ", i: "\\gamma" },
      { l: "δ", i: "\\delta" },
      { l: "ε", i: "\\varepsilon" },
      { l: "ϵ", i: "\\epsilon" },
      { l: "ζ", i: "\\zeta" },
      { l: "η", i: "\\eta" },
      { l: "θ", i: "\\theta" },
      { l: "ϑ", i: "\\vartheta" },
      { l: "ι", i: "\\iota" },
      { l: "κ", i: "\\kappa" },
      { l: "λ", i: "\\lambda" },
      { l: "μ", i: "\\mu" },
      { l: "ν", i: "\\nu" },
      { l: "ξ", i: "\\xi" },
      { l: "π", i: "\\pi" },
      { l: "ϖ", i: "\\varpi" },
      { l: "ρ", i: "\\rho" },
      { l: "ς", i: "\\varsigma" },
      { l: "σ", i: "\\sigma" },
      { l: "τ", i: "\\tau" },
      { l: "υ", i: "\\upsilon" },
      { l: "φ", i: "\\varphi" },
      { l: "ϕ", i: "\\phi" },
      { l: "χ", i: "\\chi" },
      { l: "ψ", i: "\\psi" },
      { l: "ω", i: "\\omega" },
      { l: "Γ", i: "\\Gamma" },
      { l: "Δ", i: "\\Delta" },
      { l: "Θ", i: "\\Theta" },
      { l: "Λ", i: "\\Lambda" },
      { l: "Ξ", i: "\\Xi" },
      { l: "Π", i: "\\Pi" },
      { l: "Σ", i: "\\Sigma" },
      { l: "Φ", i: "\\Phi" },
      { l: "Ψ", i: "\\Psi" },
      { l: "Ω", i: "\\Omega" },
    ],
  },
  {
    name: "其它",
    items: [
      { l: "∂", i: "\\partial", t: "偏导" },
      { l: "∇", i: "\\nabla", t: "梯度算子" },
      { l: "∞", i: "\\infty", t: "无穷" },
      { l: "′", i: "\\prime", t: "撇号" },
      { l: "∠", i: "\\angle", t: "角" },
      { l: "°", i: "^\\circ", t: "度" },
      { l: "∡", i: "\\measuredangle" },
      { l: "△", i: "\\triangle" },
      { l: "□", i: "\\square" },
      { l: "⋯", i: "\\cdots", t: "居中省略号" },
      { l: "…", i: "\\ldots", t: "底部省略号" },
      { l: "⋮", i: "\\vdots", t: "竖向省略号" },
      { l: "⋱", i: "\\ddots", t: "斜向省略号" },
      { l: "∢", i: "\\sphericalangle" },
      { l: "ℏ", i: "\\hbar" },
      { l: "ℓ", i: "\\ell" },
      { l: "ℜ", i: "\\Re" },
      { l: "ℑ", i: "\\Im" },
      { l: "℘", i: "\\wp" },
      { l: "ℵ", i: "\\aleph" },
      { l: "ı", i: "\\imath" },
      { l: "ȷ", i: "\\jmath" },
      { l: "♯", i: "\\sharp" },
      { l: "♭", i: "\\flat" },
      { l: "♮", i: "\\natural" },
      { l: "✓", i: "\\checkmark" },
      { l: "%", i: "\\%" },
      { l: "∎", i: "\\blacksquare", t: "证毕" },
    ],
  },
];

// 分类名的英文（与 SYMBOL_CATEGORIES 顺序对应；不改动数据本身）
export const CAT_EN = ["Common", "Operators", "Relations", "Arrows", "Large operators", "Sets & Logic", "Greek", "Other"];
